services:
  - type: web
    name: agenda-tareas
    env: python
    buildCommand: ./build.sh
    startCommand: cd agenda && gunicorn agenda.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: agenda-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: WEB_CONCURRENCY
        value: 4

databases:
  - name: agenda-db
    databaseName: agenda
    user: agenda